export const en = {
  homeTitle: 'Command Center',
  homeSubtitle: 'Coordinated emergency vigilance in real time.',
  getHelp: 'Get help now',
  mediaUpload: 'Media Upload',
  mediaUploadFull: 'Media Upload / ?????? ?????',
  mediaHint: 'Attach encrypted voice, camera or gallery evidence.',
  sosButton: 'SOS',
  sosSubtitle: 'Emergency Distress Signal',
  profileTooltip: 'Open profile',
  loginTitle: 'Welcome back',
  loginCta: 'Continue',
  otpTitle: 'Verify access',
  otpCta: 'Enter Command Center',
  navigation: {
    ngo: 'NGO',
    social: 'Social',
    home: 'Home/SOS',
    resources: 'Resources',
    revelation: 'Revelation',
  },
  common: {
    save: 'Save',
    add: 'Add',
    edit: 'Edit',
    cancel: 'Cancel',
    delete: 'Delete',
    retry: 'Retry',
    back: 'Back',
    on: 'ON',
    off: 'OFF',
    active: 'Active',
    inactive: 'Inactive',
    completed: 'completed',
    attachments: 'Attachments',
    noAttachments: 'No attachments yet',
    notAvailable: 'Not available',
    offlineMode: 'Offline-like mode enabled (mock).',
  },
  home: {
    sosAccessibility: 'Press and hold to activate SOS',
    sosHoldText: 'Hold',
    sosInstruction: 'Press and hold to activate',
    readinessTitle: 'Safety readiness',
    readinessAction: 'Complete setup',
    recentIncidentSubtitle: 'Recent incident',
    quickActions: {
      contacts: 'Emergency Contacts',
      safetySetup: 'Safety Setup',
      voice: 'Voice',
      spectator: 'Spectator Assist',
      reportEvidence: 'Report Evidence',
    },
  },
  media: {
    previewTitle: 'Captured evidence preview',
    previewSubtitle: 'Review the image before sending it to Revelation Desk.',
    fallbackTitle: 'Camera unavailable',
    captureInProgress: 'Opening camera...',
    permissionDenied: 'Camera permission is unavailable right now. You can choose a file instead or continue to Revelation Desk.',
    unavailable: 'Direct camera capture is not available on this device. You can choose a file or continue to Revelation Desk.',
    chooseFile: 'Choose File',
    openRevelation: 'Open Revelation',
    useInReport: 'Use In Report',
    retake: 'Retake',
    addedToReport: 'Image attached to report.',
    insertedDescription: 'Voice description added.',
  },
  voice: {
    title: 'Voice Incident Input',
    subtitle: 'Speak the incident details. If speech capture is unavailable, you can type the details manually.',
    placeholder: 'Describe what is happening, landmarks, and urgent needs',
    states: {
      idle: 'Ready',
      listening: 'Listening',
      processing: 'Processing',
      result: 'Transcript ready',
    },
    messages: {
      listening: 'Listening for your incident description.',
      processing: 'Preparing transcript...',
      resultReady: 'Transcript captured. Review before using it.',
      fallbackReady: 'Mock transcript prepared. You can edit it before use.',
      fallbackListening: 'Voice capture is limited here. Simulating quick recording flow.',
      fallbackUnavailable: 'Voice recognition is not fully supported here. Manual text remains available.',
    },
    actions: {
      start: 'Start',
      stop: 'Stop',
      processing: 'Processing',
      retry: 'Retry',
      cancel: 'Cancel',
      useDescription: 'Use This Description',
    },
    mockTranscript: 'Need immediate assistance near my current location. Please send help quickly.',
  },
  contacts: {
    title: 'Emergency Contacts',
    subtitle: 'Manage who gets notified during SOS',
    searchPlaceholder: 'Search contact or number',
    addCta: 'Add Emergency Contact',
    addTitle: 'Add Contact',
    editTitle: 'Edit Contact',
    formSubtitle: 'Set priority and SOS usage preferences',
    activeHint: 'Only active contacts are notified in SOS flow.',
    emptyTitle: 'No emergency contacts',
    emptyDescription: 'Add trusted contacts so they can receive SOS alerts.',
    deleteTitle: 'Delete Contact',
    deleteMessage: 'Remove {name} from emergency contacts?',
    fields: {
      name: 'Name*',
      phone: 'Phone*',
      alternatePhone: 'Alternate phone',
      relation: 'Relation',
      priority: 'Priority',
      activeForSos: 'Active for SOS',
      notes: 'Notes',
    },
    placeholders: {
      name: 'Enter full name',
      phone: 'Enter phone number',
      alternatePhone: 'Optional alternate number',
      notes: 'Any instructions for responders',
    },
    validation: {
      nameRequired: 'Name is required.',
      phoneRequired: 'Phone is required.',
      phoneInvalid: 'Enter a valid phone number.',
      duplicateWarning: 'This number already exists for {name}.',
    },
    relationLabels: {
      Family: 'Family',
      Friend: 'Friend',
      Guardian: 'Guardian',
      Police: 'Police',
      Neighbor: 'Neighbor',
      Other: 'Other',
    },
    priorityLabels: {
      High: 'High',
      Medium: 'Medium',
      Low: 'Low',
    },
  },
  safetySetup: {
    title: 'Safety Setup',
    subtitle: 'Review preparedness before an emergency',
    readinessTitle: 'Readiness checklist',
    checklist: {
      profileCompleted: 'Profile completed',
      contactsAdded: 'Emergency contacts added',
      locationPermission: 'Location permission enabled',
      notificationsPermission: 'Notifications permission enabled',
      micCameraOptional: 'Mic or camera enabled (optional)',
    },
    actions: {
      manageContacts: 'Manage Contacts',
      manageContactsHint: 'Add and prioritize emergency contacts.',
      permissionSetup: 'Permission Setup',
      permissionSetupHint: 'Enable required app permissions.',
      safetySettings: 'Safety Settings',
      safetySettingsHint: 'Adjust SOS behavior preferences.',
      testSos: 'Test SOS Flow',
      testSosHint: 'Run long-press, countdown and active incident demo.',
    },
  },
  permissions: {
    title: 'Permissions Setup',
    subtitle: 'Simulate readiness permissions for SOS',
    enabledLabel: 'Enabled',
    disabledLabel: 'Disabled',
    requiredHint: 'Required for SOS readiness',
    optionalHint: 'Optional but recommended',
    enable: 'Enable',
    disable: 'Disable',
    cards: {
      location: {
        title: 'Location',
        description: 'Needed for live location sharing during incidents.',
      },
      notifications: {
        title: 'Notifications',
        description: 'Needed for case updates and status alerts.',
      },
      microphone: {
        title: 'Microphone',
        description: 'Optional for voice evidence capture.',
      },
      camera: {
        title: 'Camera',
        description: 'Optional for photo/video evidence capture.',
      },
    },
  },
  safetySettings: {
    title: 'Safety Settings',
    subtitle: 'Configure default SOS behavior',
    toggles: {
      silentModeDefault: 'Silent mode default',
      autoRecord: 'Auto-record (mock)',
      continuousLocationShare: 'Continuous location share (mock)',
      vibration: 'Vibration',
      fakeCallShortcut: 'Fake call shortcut',
    },
    countdownLabel: 'Countdown duration',
    messageLanguageLabel: 'Distress message language',
    resetDefaults: 'Reset to defaults',
  },
  sosActivation: {
    title: 'SOS Activation',
    subtitle: 'Arm and trigger emergency mode',
    holdHint: 'Press and hold to arm SOS',
    holdButtonText: 'Hold to arm',
    accessibilityLongPress: 'Press and hold SOS button',
    countdownLabel: 'Sending in {seconds}s. Tap cancel to stop.',
    sending: 'Sending alerts to emergency contacts...',
    cancel: 'Cancel countdown',
    silentMode: 'Silent Mode',
    fakeCall: 'Fake Call',
    fakeCallTitle: 'Fake call started',
    fakeCallMessage: 'This is a mock shortcut for demo mode only.',
  },
  activeIncident: {
    title: 'Active Incident',
    notFoundTitle: 'Incident not found',
    notFoundDescription: 'The active incident could not be loaded.',
    timerLabel: 'Active timer',
    locationTitle: 'Location (mock)',
    notifyTitle: 'Contact notification status',
    noContacts: 'No active emergency contacts configured.',
    evidenceTitle: 'Quick evidence actions',
    photo: 'Photo',
    video: 'Video',
    voice: 'Voice',
    timelineTitle: 'Timeline preview',
    viewDetails: 'Open full case details',
    safeNow: 'I Am Safe Now',
    escalate: 'Escalate',
    callHelpline: 'Call Emergency Helpline',
  },
  safeNow: {
    title: 'Safe Confirmation',
    heading: 'Are you safe now?',
    subtitle: 'Confirm to resolve the active incident locally.',
    notePlaceholder: 'Optional note for closure',
    confirm: 'Confirm and Close Incident',
  },
  caseDetail: {
    title: 'Case Detail',
    notFoundTitle: 'Case unavailable',
    notFoundDescription: 'This case could not be found in local history.',
    headerLabel: 'Case header',
    type: 'Type',
    status: 'Status',
    date: 'Date/Time',
    locationTitle: 'Location summary',
    contactsTitle: 'Notified contacts summary',
    notifiedCount: 'Contacts notified',
    attachmentsTitle: 'Attachments summary',
    attachmentsCount: 'Attachment count',
    timelineTitle: 'Timeline',
    notesTitle: 'Notes / Description',
    resolutionNote: 'Resolution note',
  },
  spectatorAssist: {
    title: 'Spectator Assist',
    subtitle: 'Report emergency for someone else',
    typeLabel: 'Emergency type',
    detailsLabel: 'Details',
    detailsPlaceholder: 'Describe what happened, landmarks, and urgency.',
    locationToggle: 'Include my location',
    locationHint: 'Attach your current location as witness context.',
    submit: 'Submit Spectator Alert',
    validation: {
      detailsRequired: 'Please add incident details before submitting.',
    },
    types: {
      injury: 'Injury',
      harassment: 'Harassment',
      accident: 'Accident',
      fire: 'Fire',
      medical: 'Medical',
      other: 'Other',
    },
  },
  drafts: {
    title: 'Draft Reports',
    subtitle: 'Manage locally saved revelation drafts',
    resume: 'Edit / Resume',
    untitled: 'Untitled Draft',
    deleteTitle: 'Delete draft',
    deleteMessage: 'This draft will be removed from local storage.',
    emptyTitle: 'No drafts found',
    emptyDescription: 'Save a draft from Revelation to continue later.',
    createDraft: 'Create Draft',
  },
  settings: {
    title: 'Settings',
    subtitle: 'Language, safety, and demo controls',
    languageTitle: 'Language',
    languageToggle: 'Toggle app language',
    quickLinks: 'Quick links',
    roleTitle: 'Demo role switcher',
    devTitle: 'Simulation controls',
    offlineMode: 'Offline-like status',
    links: {
      safetySetup: 'Safety Setup',
      safetySettings: 'Safety Settings',
      emergencyContacts: 'Emergency Contacts',
      draftReports: 'Draft Reports',
    },
    roles: {
      citizen: 'Citizen',
      authority: 'Authority',
      ngo: 'NGO',
      admin: 'Admin',
    },
  },
  distress: {
    title: 'Distress Signal Count',
    titleNew: 'Distress History',
    historyTitle: 'Distress History',
    historySubtitle: 'Track SOS, spectator alerts, and reports',
    searchPlaceholder: 'Search by case id, type, or location',
    activeGroup: 'Active',
    recentGroup: 'Recent',
    olderGroup: 'Older',
    emptyTitle: 'No distress records',
    emptyDescription: 'New SOS, spectator, or report cases will appear here.',
    tabs: {
      sos: 'SOS',
      media: 'Media Upload',
    },
    detail: {
      date: 'Date',
      time: 'Time',
      geo: 'Geo-location',
      mediaType: 'Media type',
      media: 'Media',
      feedback: 'Feedback (if any)',
    },
  },
  revelation: {
    titleNew: 'Revelation Desk',
    subtitleNew: 'Capture evidence and submit local case entry',
    categoryLabel: 'Category',
    severityLabel: 'Severity',
    privacyLabel: 'Privacy and context',
    anonymityToggle: 'Submit anonymously',
    locationToggle: 'Include location',
    titleOptional: 'Title (optional)',
    titlePlaceholder: 'Short heading for this report',
    descriptionRequired: 'Description (required)',
    descriptionPlaceholder: 'Describe incident details clearly for responders.',
    descriptionActions: {
      voice: 'Voice Input',
      capture: 'Capture Image',
      video: 'Capture Video',
    },
    toolsTitle: 'Action tools',
    tools: {
      safetySetup: 'Safety Setup',
      safetySetupHint: 'Open readiness setup and permissions.',
      reportEvidence: 'Report Evidence',
      reportEvidenceHint: 'Add photo/video/voice evidence (mock).',
    },
    saveDraft: 'Save Draft',
    submitNow: 'Submit Report',
    draftSaved: 'Draft saved locally ({id}).',
    voiceApplied: 'Voice description added to the report.',
    imageAttached: 'Captured image attached.',
    videoAttached: 'Captured video attached.',
    categories: ['Emergency evidence', 'Public atrocity', 'Corruption', 'NGO issue', 'Other'],
    severityOptions: ['Low', 'Medium', 'High', 'Critical'],
    validation: {
      descriptionRequired: 'Description is required before submission.',
    },
  },
  resources: {
    titleNew: 'Resources',
    subtitleNew: 'Verified support channels and nearby services',
    searchPlaceholder: 'Search helplines, shelters, legal aid',
    emptyTitle: 'No resources found',
    emptyDescription: 'Try a different search term or filter.',
    quickLinks: {
      resourceHandle: 'Resource Handler',
      availableService: 'Available Service',
    },
    actions: {
      call: 'Call',
      copy: 'Copy',
      share: 'Share',
      callTitle: 'Call unavailable',
      callNotAvailable: 'This resource does not support direct calling.',
      copyTitle: 'Contact copied (mock)',
      copySuccess: 'Saved contact',
    },
  },
  ngo: {
    title: 'Partner NGO Grid',
    subtitle: 'Filter verified organisations by command level and deploy aid faster.',
    titleNew: 'NGO Partners',
    subtitleNew: 'Filter and follow verified partners',
    searchPlaceholder: 'Search NGOs, campaigns, categories',
    filterFeedback: 'Showing {level} level NGOs',
    header: {
      filter: 'Open level filter',
      history: 'Open contribution history',
    },
    scopeOptions: {
      all: 'All',
      district: 'District',
      state: 'State',
      national: 'National',
      global: 'Global',
    },
    follow: 'Follow',
    following: 'Following',
    emptyTitle: 'No NGOs found',
    emptyDescription: 'Try changing filters or search term.',
    detail: {
      title: 'NGO Detail',
      notFoundTitle: 'NGO not found',
      notFoundDescription: 'The selected NGO could not be loaded.',
      follow: 'Follow',
      following: 'Following',
      donate: 'Donate',
      share: 'Share',
      contact: 'Contact',
      tabs: {
        overview: 'Overview',
        campaigns: 'Campaigns',
        updates: 'Updates',
        transparency: 'Transparency',
        about: 'About',
      },
      fundingTitle: 'Funding progress',
      campaignsTitle: 'Active campaigns',
      updatesTitle: 'Operational updates',
      transparencyTitle: 'Transparency and contributions',
      aboutTitle: 'About this NGO',
      missionTitle: 'Mission',
      operatingAreasTitle: 'Operating areas',
      causesTitle: 'Causes served',
      contactInfoTitle: 'Contact info',
      quickStatsTitle: 'Quick stats',
      summaryWidgetTitle: 'Response summary',
      verificationTitle: 'Verification',
      raisedLabel: 'Raised',
      beneficiariesLabel: 'Beneficiaries',
      campaignsLabel: 'Campaigns',
      responseTimeLabel: 'Response time',
      allocationTitle: 'Recent allocations',
      registrationTitle: 'Registration and compliance',
      regionsTitle: 'Regions covered',
      registeredPlaceholder: 'Verified registration documents on file (mock).',
      proofBadge: 'Verified proof',
      messageFollowed: 'You are now following this NGO.',
      messageShared: 'Share options will be added in a future update.',
      messageContact: 'Contact tools are shown in About section for now.',
      support: 'Support',
      comment: 'Comment',
      shareAction: 'Share',
      campaignStatuses: {
        active: 'Active',
        urgent: 'Urgent',
        completed: 'Completed',
      },
      allocationLine: '{amount} allocated to {purpose}',
      aboutDescription: 'This is a frontend-only NGO profile with verified-looking operational and compliance details for demo use.',
      updateLine: 'Verified ground activity update {index} completed.',
      openCase: 'View full profile',
    },
    filters: {
      district: 'District',
      state: 'State',
      national: 'National',
      global: 'Global',
    },
  },
  social: {
    title: 'Field Intel Stream',
    titleNew: 'Community Feed',
    subtitleNew: 'Verified SOS updates, relief campaigns, and local alerts',
    filterLabel: 'Choose a mission focus to refine verified posts.',
    searchPlaceholder: 'Search updates, NGOs, tags, or locations',
    filterFeedback: 'Showing {category} posts',
    donate: 'Mobilise',
    progressLabel: 'secured for mission',
    emptyTitle: 'No posts found',
    emptyDescription: 'Try another category or search term.',
    header: {
      search: 'Search feed',
      filter: 'Open scope filter',
      notifications: 'Open feed notifications',
      profile: 'Open profile quick actions',
    },
    scopeOptions: {
      all: 'All',
      district: 'District',
      state: 'State',
      national: 'National',
      global: 'Global',
    },
    scopeFeedback: 'Scope: {scope}',
    filters: {
      all: 'All',
      verified: 'Verified',
      relief: 'Relief',
      medical: 'Medical',
      awareness: 'Awareness',
      nearby: 'Nearby',
    },
    actions: {
      like: 'Like',
      liked: 'Liked',
      comment: 'Comment',
      share: 'Share',
      donate: 'Donate',
      supported: 'Supported',
      save: 'Save post',
      unsave: 'Unsave post',
      more: 'More options',
    },
    composer: {
      prompt: 'Share an update, report, or request help...',
      actions: {
        photo: 'Photo',
        video: 'Video',
        alert: 'Alert',
        fundraiser: 'Fundraiser',
      },
    },
    highlights: {
      title: 'SOS Highlights',
      items: [
        { key: 'nearbyAlerts', title: 'Nearby Alerts', countLabel: '12 active' },
        { key: 'urgentCampaigns', title: 'Urgent Campaigns', countLabel: '7 need support' },
        { key: 'verifiedNgos', title: 'Verified NGOs', countLabel: '43 trusted orgs' },
        { key: 'medicalRequests', title: 'Medical Requests', countLabel: '9 open requests' },
        { key: 'shelterUpdates', title: 'Shelter Updates', countLabel: '5 shelters updated' },
        { key: 'awarenessDrive', title: 'Awareness Drive', countLabel: '14 live drives' },
      ],
    },
    feed: {
      seeMore: 'See more',
      seeLess: 'See less',
      viewAllComments: 'View all comments',
      commentPlaceholder: 'Write a comment (mock)...',
      verifiedLabel: 'Verified',
      urgentLabel: 'Urgent',
      justNow: 'Just now',
      minutesAgo: '{count}m ago',
      hoursAgo: '{count}h ago',
      daysAgo: '{count}d ago',
      urgentCta: 'Needs support within {hours} hrs',
      donorsLabel: '{count} supporters',
      commentsLabel: 'comments',
      sharesLabel: 'shares',
      supportersLabel: 'supporters',
    },
    sidebars: {
      leftTitle: 'Shortcuts',
      links: {
        allFeed: 'All Feed',
        savedPosts: 'My Saved Posts',
        verifiedNgos: 'Verified NGOs',
        urgentAppeals: 'Urgent Appeals',
        medicalHelp: 'Medical Help',
        awareness: 'Awareness',
      },
      widgets: {
        urgentCampaigns: 'Urgent Campaigns',
        nearbyResources: 'Nearby Resources',
        topContributors: 'Top Contributors',
        trendingTags: 'Trending Tags',
        safetyTips: 'Safety Tips',
      },
      tips: {
        tipOne: 'Verify source handles before sharing emergency posts.',
        tipTwo: 'Use SOS for immediate danger and attach clear location context.',
        tipThree: 'Escalate only verified campaigns to community groups.',
      },
      tags: ['#safecorridor', '#rapidrelief', '#womenhelpdesk', '#communitywatch'],
      empty: 'No updates in this widget yet.',
    },
    states: {
      loadingTitle: 'Loading feed',
      loadingDescription: 'Fetching verified community updates.',
      emptyTitle: 'No matching posts',
      emptyDescription: 'Try changing filters or search keywords.',
      errorTitle: 'Feed unavailable',
      errorDescription: 'Could not refresh the feed right now. Please retry.',
      retry: 'Retry',
      resetFilters: 'Reset filters',
    },
    toasts: {
      savedFilterOn: 'Saved posts filter enabled',
      savedFilterOff: 'Saved posts filter cleared',
      scopeUpdated: 'Scope set to {scope}',
      profileSoon: 'Profile quick actions coming soon',
      shareMock: 'Share sheet opened (mock)',
      copyMock: 'Post link copied (mock)',
      donationMock: 'Mock pledge recorded: Rs {amount}',
    },
    detail: {
      title: 'Post Detail',
      notFoundTitle: 'Post not found',
      notFoundDescription: 'The selected post is unavailable in local feed.',
      openCase: 'Open full details',
      descriptionTitle: 'Update description',
      campaignTitle: 'Campaign summary',
      engagementTitle: 'Engagement summary',
    },
    modals: {
      comingSoonTitle: 'Posting coming soon',
      comingSoonDescription: 'Create post flow will be added in a future update.',
      comingSoonAction: '{action} posting is coming soon.',
      shareTitle: 'Share post',
      shareDescription: 'Choose how to share this update from {author}.',
      shareOptions: {
        copy: 'Copy link',
        forward: 'Forward',
      },
      donateTitle: 'Support campaign',
      donateDescription: 'Select a mock contribution for {author}.',
      donateHint: 'Demo only. No payment will be processed.',
      notificationsTitle: 'Feed notifications',
      notificationsDescription: 'Relief requests, verified alerts, and comment updates will appear here (mock).',
      commentsTitle: 'Comments panel',
      commentsDescription: 'Full comments thread is in demo mode. You can preview comments in each post.',
      imageTitle: 'Image preview',
      close: 'Close',
    },
  },
  dashboard: {
    backToCitizen: 'Citizen Mode',
    authority: {
      title: 'Authority Dashboard',
      subtitle: 'Incident queue and tactical response actions',
      searchPlaceholder: 'Search by case id or location',
      emptyTitle: 'No queue items',
      emptyDescription: 'No incidents match current filters.',
      actions: {
        accept: 'Accept',
        enRoute: 'En Route',
        onScene: 'On Scene',
        resolved: 'Resolved',
        uploadProof: 'Upload Proof (mock)',
      },
    },
    ngo: {
      title: 'NGO Dashboard',
      subtitle: 'Campaigns, aid requests, and impact feed',
      metrics: {
        raised: 'Raised',
        goal: 'Goal',
        campaigns: 'Campaigns',
      },
      campaignsTitle: 'Campaigns',
      aidTitle: 'Aid requests',
      impactTitle: 'Impact updates',
    },
    admin: {
      title: 'Admin Dashboard',
      subtitle: 'Moderation, verification, and transparency controls',
      metrics: {
        pending: 'Pending reviews',
        verifiedNgos: 'Verified NGOs',
        flagged: 'Flagged items',
      },
      moderationTitle: 'Moderation queue',
      verificationTitle: 'NGO verification list',
      flaggedTitle: 'Flagged content',
    },
  },
  confirmation: {
    reportTitle: 'Report received',
    reportSubtitle: 'Your report has been saved locally with a case ID.',
    spectatorTitle: 'Spectator alert received',
    spectatorSubtitle: 'Bystander alert saved and added to local history.',
    sosTitle: 'SOS activated',
    sosSubtitle: 'Emergency alert has been triggered in demo mode.',
    caseIdLabel: 'Case ID',
    primary: 'Back to dashboard',
    secondary: 'View case detail',
  },
  profile: {
    title: 'Profile',
    subtitle: 'Manage account and safety tools',
    sections: {
      account: 'Account',
      safety: 'Safety & SOS',
      support: 'Support',
    },
    links: {
      personalDetails: 'Personal Details',
      contributions: 'My Contributions',
      sosHistory: 'SOS History',
      emergencyContacts: 'Emergency Contacts',
      safetySetup: 'Safety Setup',
      safetySettings: 'Safety Settings',
      draftReports: 'Draft Reports',
      demoRoleSwitcher: 'Demo Role Switcher',
      emergencyServices: 'Emergency Services',
      about: 'About Sankatmochan',
    },
  },
  resourcesHandle: {
    title: 'Resource Handler',
    subtitle: 'Resource management',
    used: 'Resources Used',
    received: 'Resources Received',
    reservoir: 'Reservoir',
  },
  services: {
    title: 'Available Service',
    states: 'List Of States',
    districts: 'List Of Districts',
    list: 'List',
  },
  contributions: {
    made: 'Contribution Made',
    received: 'Contribution Received',
  },
};
