import { en } from './en';

export const hi = {
  ...en,
  homeTitle: 'Command Kendra',
  homeSubtitle: 'Real-time samyojit emergency satarkata.',
  getHelp: 'Abhi madad lein',
  mediaUpload: 'Media Upload',
  mediaUploadFull: 'Media Upload / Media Upload',
  mediaHint: 'Voice, camera ya gallery evidence joden.',
  sosSubtitle: 'Aapatkalin sankat sanket',
  profileTooltip: 'Profile kholen',
  loginTitle: 'Wapas swagat hai',
  loginCta: 'Jari rakhen',
  otpTitle: 'Pravesh satyapit karein',
  otpCta: 'Command Center mein pravesh karein',
  navigation: {
    ...en.navigation,
    ngo: 'NGO',
    social: 'Social',
    home: 'Home/SOS',
    resources: 'Sansaadhan',
    revelation: 'Revelation',
  },
  common: {
    ...en.common,
    save: 'Save',
    add: 'Joden',
    edit: 'Edit',
    cancel: 'Radd karein',
    delete: 'Hatayein',
    retry: 'Dobara koshish',
    back: 'Wapas',
    on: 'CHALU',
    off: 'BAND',
    active: 'Sakriya',
    inactive: 'Nishkriya',
    completed: 'poorn',
    attachments: 'Attachments',
    noAttachments: 'Abhi koi attachment nahi',
    notAvailable: 'Upalabdh nahi',
    offlineMode: 'Offline-jaisa mode sakriya (mock).',
  },
  home: {
    ...en.home,
    sosAccessibility: 'SOS activate karne ke liye press and hold karein',
    sosHoldText: 'Hold',
    sosInstruction: 'Activate karne ke liye press and hold karein',
    readinessTitle: 'Suraksha taiyari',
    readinessAction: 'Setup poora karein',
    recentIncidentSubtitle: 'Haal ka incident',
    quickActions: {
      contacts: 'Emergency Contacts',
      safetySetup: 'Safety Setup',
      voice: 'Voice',
      spectator: 'Spectator Assist',
      reportEvidence: 'Evidence Report',
    },
  },
  media: {
    previewTitle: 'Captured evidence preview',
    previewSubtitle: 'Image ko Revelation Desk mein bhejne se pehle review karein.',
    fallbackTitle: 'Camera unavailable',
    captureInProgress: 'Camera khola ja raha hai...',
    permissionDenied: 'Camera permission abhi upalabdh nahi hai. Aap file choose kar sakte hain ya Revelation Desk khol sakte hain.',
    unavailable: 'Direct camera capture is device par upalabdh nahi hai. File choose karein ya Revelation Desk par jaayein.',
    chooseFile: 'File Chunein',
    openRevelation: 'Revelation Kholen',
    useInReport: 'Report Mein Use Karein',
    retake: 'Phir Se Le',
    addedToReport: 'Image report ke saath jod di gayi.',
    insertedDescription: 'Voice description jod di gayi.',
  },
  voice: {
    title: 'Voice Incident Input',
    subtitle: 'Incident details bolkar batayein. Agar speech capture available na ho to aap manually bhi likh sakte hain.',
    placeholder: 'Batayein kya ho raha hai, landmarks aur urgent needs',
    states: {
      idle: 'Ready',
      listening: 'Listening',
      processing: 'Processing',
      result: 'Transcript ready',
    },
    messages: {
      listening: 'Aapki incident description suni ja rahi hai.',
      processing: 'Transcript taiyar ki ja rahi hai...',
      resultReady: 'Transcript capture ho gayi. Use se pehle review karein.',
      fallbackReady: 'Mock transcript taiyar hai. Use se pehle edit kar sakte hain.',
      fallbackListening: 'Voice capture yahan simit hai. Quick recording flow simulate kiya ja raha hai.',
      fallbackUnavailable: 'Voice recognition yahan poori tarah supported nahi hai. Manual text abhi bhi available hai.',
    },
    actions: {
      start: 'Start',
      stop: 'Stop',
      processing: 'Processing',
      retry: 'Retry',
      cancel: 'Cancel',
      useDescription: 'Use This Description',
    },
    mockTranscript: 'Mujhe turant madad chahiye. Main apni current location ke paas hoon, kripya jaldi sahayata bhejein.',
  },
  contacts: {
    ...en.contacts,
    title: 'Aapatkalin sampark',
    subtitle: 'SOS ke dauran kise notify karna hai',
    searchPlaceholder: 'Sampark ya number khojen',
    addCta: 'Emergency Contact joden',
    addTitle: 'Contact joden',
    editTitle: 'Contact edit karein',
    formSubtitle: 'Priority aur SOS settings set karein',
    activeHint: 'Sirf active contacts ko SOS alert jayega.',
    emptyTitle: 'Koi emergency contact nahi',
    emptyDescription: 'Vishwasniya contacts joden taaki SOS alert pahunch sake.',
    deleteTitle: 'Contact hatayein',
    deleteMessage: '{name} ko emergency list se hatana hai?',
    fields: {
      ...en.contacts.fields,
      name: 'Naam*',
      phone: 'Phone*',
      alternatePhone: 'Alternate phone',
      relation: 'Relation',
      priority: 'Priority',
      activeForSos: 'SOS ke liye active',
      notes: 'Notes',
    },
    placeholders: {
      ...en.contacts.placeholders,
      name: 'Poora naam darj karein',
      phone: 'Phone number darj karein',
      alternatePhone: 'Vikalpik number',
      notes: 'Responders ke liye nirdesh',
    },
    validation: {
      ...en.contacts.validation,
      nameRequired: 'Naam avashyak hai.',
      phoneRequired: 'Phone avashyak hai.',
      phoneInvalid: 'Sahi phone number darj karein.',
      duplicateWarning: 'Yeh number pehle se {name} ke liye maujood hai.',
    },
    relationLabels: {
      Family: 'Parivaar',
      Friend: 'Mitra',
      Guardian: 'Guardian',
      Police: 'Police',
      Neighbor: 'Padosi',
      Other: 'Anya',
    },
    priorityLabels: {
      High: 'Ucch',
      Medium: 'Madhyam',
      Low: 'Nimn',
    },
  },
  safetySetup: {
    ...en.safetySetup,
    title: 'Safety Setup',
    subtitle: 'Emergency se pehle taiyari check karein',
    readinessTitle: 'Readiness checklist',
    checklist: {
      profileCompleted: 'Profile poora',
      contactsAdded: 'Emergency contacts jode gaye',
      locationPermission: 'Location permission enabled',
      notificationsPermission: 'Notifications permission enabled',
      micCameraOptional: 'Mic ya camera enabled (optional)',
    },
    actions: {
      manageContacts: 'Contacts manage karein',
      manageContactsHint: 'Contacts add karein aur priority set karein.',
      permissionSetup: 'Permission Setup',
      permissionSetupHint: 'Required permissions enable karein.',
      safetySettings: 'Safety Settings',
      safetySettingsHint: 'SOS behavior preferences update karein.',
      testSos: 'SOS Flow Test',
      testSosHint: 'Long press, countdown aur active mode demo.',
    },
  },
  permissions: {
    ...en.permissions,
    title: 'Permission Setup',
    subtitle: 'SOS ke liye mock permission readiness',
    enabledLabel: 'Enabled',
    disabledLabel: 'Disabled',
    requiredHint: 'SOS readiness ke liye zaroori',
    optionalHint: 'Vikalpik par sujhaavit',
    enable: 'Enable',
    disable: 'Disable',
    cards: {
      location: {
        title: 'Location',
        description: 'Live location sharing ke liye zaroori.',
      },
      notifications: {
        title: 'Notifications',
        description: 'Case updates aur alert status ke liye.',
      },
      microphone: {
        title: 'Microphone',
        description: 'Voice evidence ke liye vikalpik.',
      },
      camera: {
        title: 'Camera',
        description: 'Photo/video evidence ke liye vikalpik.',
      },
    },
  },
  safetySettings: {
    ...en.safetySettings,
    title: 'Safety Settings',
    subtitle: 'Default SOS behavior set karein',
    toggles: {
      silentModeDefault: 'Default silent mode',
      autoRecord: 'Auto-record (mock)',
      continuousLocationShare: 'Continuous location share (mock)',
      vibration: 'Vibration',
      fakeCallShortcut: 'Fake call shortcut',
    },
    countdownLabel: 'Countdown duration',
    messageLanguageLabel: 'Distress message language',
    resetDefaults: 'Defaults reset karein',
  },
  sosActivation: {
    ...en.sosActivation,
    title: 'SOS Activation',
    subtitle: 'Emergency mode arm aur trigger karein',
    holdHint: 'SOS arm karne ke liye press and hold karein',
    holdButtonText: 'Hold to arm',
    accessibilityLongPress: 'SOS button press and hold',
    countdownLabel: '{seconds}s mein send hoga. Cancel tap karein.',
    sending: 'Emergency contacts ko alert bheja ja raha hai...',
    cancel: 'Countdown cancel',
    silentMode: 'Silent Mode',
    fakeCall: 'Fake Call',
    fakeCallTitle: 'Fake call shuru',
    fakeCallMessage: 'Yeh sirf demo mode ke liye mock shortcut hai.',
  },
  activeIncident: {
    ...en.activeIncident,
    title: 'Active Incident',
    notFoundTitle: 'Incident nahi mila',
    notFoundDescription: 'Active incident load nahi ho saka.',
    timerLabel: 'Active timer',
    locationTitle: 'Location (mock)',
    notifyTitle: 'Contact notification status',
    noContacts: 'Koi active emergency contact configure nahi hai.',
    evidenceTitle: 'Quick evidence actions',
    timelineTitle: 'Timeline preview',
    viewDetails: 'Poora case detail dekhein',
    safeNow: 'Main ab surakshit hoon',
    escalate: 'Escalate',
    callHelpline: 'Emergency helpline call karein',
  },
  safeNow: {
    ...en.safeNow,
    title: 'Safe Confirmation',
    heading: 'Kya aap ab surakshit hain?',
    subtitle: 'Confirm karte hi incident locally resolve ho jayega.',
    notePlaceholder: 'Vikalpik note',
    confirm: 'Confirm aur incident close karein',
  },
  caseDetail: {
    ...en.caseDetail,
    title: 'Case Detail',
    notFoundTitle: 'Case upalabdh nahi',
    notFoundDescription: 'Yeh case local history mein nahi mila.',
    headerLabel: 'Case header',
    type: 'Prakar',
    status: 'Sthiti',
    date: 'Tareekh/Time',
    locationTitle: 'Location summary',
    contactsTitle: 'Notified contacts summary',
    notifiedCount: 'Notified contacts',
    attachmentsTitle: 'Attachments summary',
    attachmentsCount: 'Attachment count',
    timelineTitle: 'Timeline',
    notesTitle: 'Notes / Description',
    resolutionNote: 'Resolution note',
  },
  spectatorAssist: {
    ...en.spectatorAssist,
    title: 'Spectator Assist',
    subtitle: 'Kisi aur ke liye emergency report karein',
    typeLabel: 'Emergency type',
    detailsLabel: 'Details',
    detailsPlaceholder: 'Kya hua, landmarks aur urgency likhein.',
    locationToggle: 'Meri location include karein',
    locationHint: 'Witness context ke liye location attach karein.',
    submit: 'Spectator Alert submit karein',
    validation: {
      detailsRequired: 'Submit se pehle details darj karein.',
    },
    types: {
      injury: 'Chot',
      harassment: 'Utpeedan',
      accident: 'Durghatna',
      fire: 'Aag',
      medical: 'Medical',
      other: 'Anya',
    },
  },
  drafts: {
    ...en.drafts,
    title: 'Draft Reports',
    subtitle: 'Local saved revelation drafts manage karein',
    resume: 'Edit / Resume',
    untitled: 'Untitled Draft',
    deleteTitle: 'Draft hatayein',
    deleteMessage: 'Yeh draft local storage se remove ho jayega.',
    emptyTitle: 'Koi draft nahi mila',
    emptyDescription: 'Baad mein continue karne ke liye draft save karein.',
    createDraft: 'Draft banayein',
  },
  settings: {
    ...en.settings,
    title: 'Settings',
    subtitle: 'Bhasha, safety aur demo controls',
    languageTitle: 'Bhasha',
    languageToggle: 'App language badlein',
    quickLinks: 'Quick links',
    roleTitle: 'Demo role switcher',
    devTitle: 'Simulation controls',
    offlineMode: 'Offline-jaisi status',
    links: {
      safetySetup: 'Safety Setup',
      safetySettings: 'Safety Settings',
      emergencyContacts: 'Emergency Contacts',
      draftReports: 'Draft Reports',
    },
    roles: {
      citizen: 'Nagrik',
      authority: 'Pradhikaran',
      ngo: 'NGO',
      admin: 'Admin',
    },
  },
  distress: {
    ...en.distress,
    titleNew: 'Distress History',
    historyTitle: 'Distress History',
    historySubtitle: 'SOS, spectator alerts aur reports track karein',
    searchPlaceholder: 'Case id, type ya location se search karein',
    activeGroup: 'Active',
    recentGroup: 'Recent',
    olderGroup: 'Older',
    emptyTitle: 'Koi distress record nahi',
    emptyDescription: 'Naye SOS ya reports yahan dikhengi.',
  },
  revelation: {
    ...en.revelation,
    titleNew: 'Revelation Desk',
    subtitleNew: 'Evidence capture karein aur local case entry banayein',
    categoryLabel: 'Category',
    severityLabel: 'Severity',
    privacyLabel: 'Privacy aur context',
    anonymityToggle: 'Anonymous submit karein',
    locationToggle: 'Location include karein',
    titleOptional: 'Title (optional)',
    titlePlaceholder: 'Report ka short heading',
    descriptionRequired: 'Description (required)',
    descriptionPlaceholder: 'Incident details clear tarike se likhein.',
    descriptionActions: {
      voice: 'Voice Input',
      capture: 'Capture Image',
      video: 'Capture Video',
    },
    toolsTitle: 'Action tools',
    tools: {
      safetySetup: 'Safety Setup',
      safetySetupHint: 'Readiness setup aur permissions kholen.',
      reportEvidence: 'Report Evidence',
      reportEvidenceHint: 'Photo/video/voice evidence add karein (mock).',
    },
    saveDraft: 'Draft save karein',
    submitNow: 'Report submit karein',
    draftSaved: 'Draft local save hua ({id}).',
    voiceApplied: 'Voice description report mein jod di gayi.',
    imageAttached: 'Captured image attach ho gayi.',
    videoAttached: 'Captured video attach ho gaya.',
    categories: ['Emergency evidence', 'Public atrocity', 'Corruption', 'NGO issue', 'Other'],
    severityOptions: ['Low', 'Medium', 'High', 'Critical'],
    validation: {
      descriptionRequired: 'Submit se pehle description zaroori hai.',
    },
  },
  resources: {
    ...en.resources,
    titleNew: 'Sansaadhan',
    subtitleNew: 'Verified support channels aur nearby services',
    searchPlaceholder: 'Helplines, shelter, legal aid khojen',
    emptyTitle: 'Koi resource nahi mila',
    emptyDescription: 'Alag search term ya filter try karein.',
    quickLinks: {
      resourceHandle: 'Resource Handler',
      availableService: 'Available Service',
    },
    actions: {
      call: 'Call',
      copy: 'Copy',
      share: 'Share',
      callTitle: 'Call unavailable',
      callNotAvailable: 'Yeh resource direct calling support nahi karta.',
      copyTitle: 'Contact copied (mock)',
      copySuccess: 'Saved contact',
    },
  },
  ngo: {
    ...en.ngo,
    titleNew: 'NGO Partners',
    subtitleNew: 'Verified partners filter aur follow karein',
    searchPlaceholder: 'NGO, campaign, category search karein',
    filterFeedback: '{level} level NGOs dikh rahe hain',
    header: {
      filter: 'Level filter kholen',
      history: 'Contribution history kholen',
    },
    scopeOptions: {
      all: 'All',
      district: 'District',
      state: 'State',
      national: 'National',
      global: 'Global',
    },
    follow: 'Follow',
    following: 'Following',
    emptyTitle: 'Koi NGO nahi mila',
    emptyDescription: 'Filters ya search term badlein.',
    detail: {
      title: 'NGO Detail',
      notFoundTitle: 'NGO nahi mila',
      notFoundDescription: 'Selected NGO load nahi ho saka.',
      follow: 'Follow',
      following: 'Following',
      donate: 'Donate',
      share: 'Share',
      contact: 'Contact',
      tabs: {
        overview: 'Overview',
        campaigns: 'Campaigns',
        updates: 'Updates',
        transparency: 'Transparency',
        about: 'About',
      },
      fundingTitle: 'Funding progress',
      campaignsTitle: 'Active campaigns',
      updatesTitle: 'Operational updates',
      transparencyTitle: 'Transparency and contributions',
      aboutTitle: 'About this NGO',
      missionTitle: 'Mission',
      operatingAreasTitle: 'Operating areas',
      causesTitle: 'Causes served',
      contactInfoTitle: 'Contact info',
      quickStatsTitle: 'Quick stats',
      summaryWidgetTitle: 'Response summary',
      verificationTitle: 'Verification',
      raisedLabel: 'Raised',
      beneficiariesLabel: 'Beneficiaries',
      campaignsLabel: 'Campaigns',
      responseTimeLabel: 'Response time',
      allocationTitle: 'Recent allocations',
      registrationTitle: 'Registration and compliance',
      regionsTitle: 'Regions covered',
      registeredPlaceholder: 'Verified registration documents on file (mock).',
      proofBadge: 'Verified proof',
      messageFollowed: 'Ab aap is NGO ko follow kar rahe hain.',
      messageShared: 'Share options future update mein add honge.',
      messageContact: 'Contact tools abhi About section mein dikhaye gaye hain.',
      support: 'Support',
      comment: 'Comment',
      shareAction: 'Share',
      campaignStatuses: {
        active: 'Active',
        urgent: 'Urgent',
        completed: 'Completed',
      },
      allocationLine: '{purpose} ke liye {amount} allocate hua',
      aboutDescription: 'Yeh demo ke liye ek frontend-only NGO profile hai jisme verified-jaisi operational aur compliance details dikhayi gayi hain.',
      updateLine: 'Verified ground activity update {index} complete hui.',
      openCase: 'Full profile dekhein',
    },
    filters: {
      district: 'District',
      state: 'State',
      national: 'National',
      global: 'Global',
    },
  },
  social: {
    ...en.social,
    titleNew: 'Samudayik Feed',
    subtitleNew: 'Verified SOS updates, relief campaigns aur local alerts',
    searchPlaceholder: 'Updates, NGO, tags ya location search karein',
    filterFeedback: '{category} posts dikh rahi hain',
    emptyTitle: 'Koi post nahi mili',
    emptyDescription: 'Dusri category ya search term try karein.',
    header: {
      search: 'Feed search karein',
      filter: 'Scope filter kholen',
      notifications: 'Feed notifications kholen',
      profile: 'Profile quick actions kholen',
    },
    scopeOptions: {
      all: 'All',
      district: 'District',
      state: 'State',
      national: 'National',
      global: 'Global',
    },
    scopeFeedback: 'Scope: {scope}',
    filters: {
      all: 'Sabhi',
      verified: 'Verified',
      relief: 'Relief',
      medical: 'Medical',
      awareness: 'Awareness',
      nearby: 'Nearby',
    },
    actions: {
      like: 'Like',
      liked: 'Liked',
      comment: 'Comment',
      share: 'Share',
      donate: 'Donate',
      supported: 'Supported',
      save: 'Post save karein',
      unsave: 'Saved hataein',
      more: 'Aur options',
    },
    composer: {
      prompt: 'Update share karein, report karein, ya madad maangein...',
      actions: {
        photo: 'Photo',
        video: 'Video',
        alert: 'Alert',
        fundraiser: 'Fundraiser',
      },
    },
    highlights: {
      title: 'SOS Highlights',
      items: [
        { key: 'nearbyAlerts', title: 'Nearby Alerts', countLabel: '12 active' },
        { key: 'urgentCampaigns', title: 'Urgent Campaigns', countLabel: '7 ko support chahiye' },
        { key: 'verifiedNgos', title: 'Verified NGOs', countLabel: '43 trusted orgs' },
        { key: 'medicalRequests', title: 'Medical Requests', countLabel: '9 open requests' },
        { key: 'shelterUpdates', title: 'Shelter Updates', countLabel: '5 shelter updated' },
        { key: 'awarenessDrive', title: 'Awareness Drive', countLabel: '14 live drives' },
      ],
    },
    feed: {
      seeMore: 'Aur dekhein',
      seeLess: 'Kam dekhein',
      viewAllComments: 'Saare comments dekhein',
      commentPlaceholder: 'Comment likhein (mock)...',
      verifiedLabel: 'Verified',
      urgentLabel: 'Urgent',
      justNow: 'Abhi',
      minutesAgo: '{count}m pehle',
      hoursAgo: '{count}h pehle',
      daysAgo: '{count}d pehle',
      urgentCta: '{hours} ghante mein support chahiye',
      donorsLabel: '{count} supporters',
      commentsLabel: 'comments',
      sharesLabel: 'shares',
      supportersLabel: 'supporters',
    },
    sidebars: {
      leftTitle: 'Shortcuts',
      links: {
        allFeed: 'All Feed',
        savedPosts: 'My Saved Posts',
        verifiedNgos: 'Verified NGOs',
        urgentAppeals: 'Urgent Appeals',
        medicalHelp: 'Medical Help',
        awareness: 'Awareness',
      },
      widgets: {
        urgentCampaigns: 'Urgent Campaigns',
        nearbyResources: 'Nearby Resources',
        topContributors: 'Top Contributors',
        trendingTags: 'Trending Tags',
        safetyTips: 'Safety Tips',
      },
      tips: {
        tipOne: 'Emergency post share karne se pehle source handle verify karein.',
        tipTwo: 'Immediate danger mein SOS use karein aur clear location jodein.',
        tipThree: 'Sirf verified campaigns ko community groups mein escalate karein.',
      },
      tags: ['#safecorridor', '#rapidrelief', '#womenhelpdesk', '#communitywatch'],
      empty: 'Is widget mein abhi koi update nahi hai.',
    },
    states: {
      loadingTitle: 'Feed load ho rahi hai',
      loadingDescription: 'Verified community updates fetch ki ja rahi hain.',
      emptyTitle: 'Koi matching post nahi mili',
      emptyDescription: 'Filters ya search keywords badal kar dekhein.',
      errorTitle: 'Feed unavailable',
      errorDescription: 'Feed refresh nahi ho paayi. Dobara try karein.',
      retry: 'Retry',
      resetFilters: 'Filters reset karein',
    },
    toasts: {
      savedFilterOn: 'Saved posts filter ON',
      savedFilterOff: 'Saved posts filter OFF',
      scopeUpdated: 'Scope set hua: {scope}',
      profileSoon: 'Profile quick actions jaldi aa rahe hain',
      shareMock: 'Share sheet khul gayi (mock)',
      copyMock: 'Post link copy hua (mock)',
      donationMock: 'Mock pledge record hua: Rs {amount}',
    },
    detail: {
      title: 'Post Detail',
      notFoundTitle: 'Post nahi mili',
      notFoundDescription: 'Selected post local feed mein available nahi hai.',
      openCase: 'Full details dekhein',
      descriptionTitle: 'Update description',
      campaignTitle: 'Campaign summary',
      engagementTitle: 'Engagement summary',
    },
    modals: {
      comingSoonTitle: 'Posting feature jaldi aa rahi hai',
      comingSoonDescription: 'Create post flow agle update mein add hoga.',
      comingSoonAction: '{action} posting jaldi available hogi.',
      shareTitle: 'Post share karein',
      shareDescription: '{author} ki update kaise share karni hai chunen.',
      shareOptions: {
        copy: 'Link copy karein',
        forward: 'Forward',
      },
      donateTitle: 'Campaign support karein',
      donateDescription: '{author} ke liye mock contribution chunen.',
      donateHint: 'Demo only. Koi payment process nahi hoga.',
      notificationsTitle: 'Feed notifications',
      notificationsDescription: 'Relief requests, verified alerts aur comment updates yahan dikhenge (mock).',
      commentsTitle: 'Comments panel',
      commentsDescription: 'Full comments thread demo mode mein hai. Post card par preview dekh sakte hain.',
      imageTitle: 'Image preview',
      close: 'Band karein',
    },
  },
  dashboard: {
    ...en.dashboard,
    backToCitizen: 'Citizen Mode',
    authority: {
      ...en.dashboard.authority,
      title: 'Authority Dashboard',
      subtitle: 'Incident queue aur response actions',
      searchPlaceholder: 'Case id ya location search karein',
      emptyTitle: 'Queue khali hai',
      emptyDescription: 'Current filters ke hisaab se incidents nahi mile.',
      actions: {
        accept: 'Accept',
        enRoute: 'En Route',
        onScene: 'On Scene',
        resolved: 'Resolved',
        uploadProof: 'Upload Proof (mock)',
      },
    },
    ngo: {
      ...en.dashboard.ngo,
      title: 'NGO Dashboard',
      subtitle: 'Campaigns, aid requests aur impact feed',
      metrics: {
        raised: 'Raised',
        goal: 'Goal',
        campaigns: 'Campaigns',
      },
      campaignsTitle: 'Campaigns',
      aidTitle: 'Aid requests',
      impactTitle: 'Impact updates',
    },
    admin: {
      ...en.dashboard.admin,
      title: 'Admin Dashboard',
      subtitle: 'Moderation, verification aur transparency controls',
      metrics: {
        pending: 'Pending reviews',
        verifiedNgos: 'Verified NGOs',
        flagged: 'Flagged items',
      },
      moderationTitle: 'Moderation queue',
      verificationTitle: 'NGO verification list',
      flaggedTitle: 'Flagged content',
    },
  },
  confirmation: {
    ...en.confirmation,
    reportTitle: 'Report receive hui',
    reportSubtitle: 'Aapki report local case ID ke saath save ho gayi hai.',
    spectatorTitle: 'Spectator alert receive hua',
    spectatorSubtitle: 'Bystander alert local history mein add ho gaya hai.',
    sosTitle: 'SOS activate hua',
    sosSubtitle: 'Demo mode mein emergency alert trigger hua.',
    caseIdLabel: 'Case ID',
    primary: 'Dashboard par wapas',
    secondary: 'Case detail dekhein',
  },
  profile: {
    ...en.profile,
    title: 'Profile',
    subtitle: 'Account aur safety tools manage karein',
    sections: {
      account: 'Account',
      safety: 'Safety & SOS',
      support: 'Support',
    },
    links: {
      personalDetails: 'Personal Details',
      contributions: 'My Contributions',
      sosHistory: 'SOS History',
      emergencyContacts: 'Emergency Contacts',
      safetySetup: 'Safety Setup',
      safetySettings: 'Safety Settings',
      draftReports: 'Draft Reports',
      demoRoleSwitcher: 'Demo Role Switcher',
      emergencyServices: 'Emergency Services',
      about: 'About Sankatmochan',
    },
  },
  resourcesHandle: {
    title: 'Resource Handler',
    subtitle: 'Sansaadhan prabandhan',
    used: 'Resources Used',
    received: 'Resources Received',
    reservoir: 'Reservoir',
  },
  services: {
    title: 'Available Service',
    states: 'List of States',
    districts: 'List of Districts',
    list: 'List',
  },
  contributions: {
    made: 'Contribution Made',
    received: 'Contribution Received',
  },
};
