export const STRINGS = {
  en: {
    homeTitle: 'Command Center',
    homeSubtitle: 'Coordinated emergency vigilance in real time.',
    getHelp: 'Get help now',
    mediaUpload: 'Media Upload',
    mediaUploadFull: 'Media Upload / मीडिया अपलोड',
    mediaHint: 'Attach encrypted voice, camera or gallery evidence.',
    sosButton: 'SOS',
    sosSubtitle: 'Emergency Distress Signal',
    profileTooltip: 'Open profile',
    navigation: {
      ngo: 'NGO',
      social: 'Social Media',
      home: 'Home/SOS',
      resources: 'Resources',
      revelation: 'Revelation',
    },
    revelationTitle: 'Revelation Desk',
    revelationPlaceholder: 'Describe the incident, locations, vehicles, or accompanying risks…',
    revelationHint: 'Voice, camera or gallery attachments recommended.',
    revelationSubmit: 'Submit Revelation',
    loginTitle: 'Welcome back',
    loginCta: 'Continue',
    otpTitle: 'Verify access',
    otpCta: 'Enter Command Center',
    confirmationTitle: 'Signal received',
    confirmationSubtitle: 'Our field teams are mobilising and will contact you soon.',
    confirmationDetails:
      'The unified command center has acknowledged your submission and assigned it a verified case ID.',
    confirmationPrimary: 'Back to dashboard',
    confirmationSecondary: 'Share report',
    ngo: {
      title: 'Partner NGO Grid',
      subtitle: 'Filter verified organisations by command level and deploy aid faster.',
      filters: {
        district: 'District Command',
        state: 'State Nodes',
        national: 'National',
        global: 'Global',
      },
      raisedLabel: (raised, goal) => `₹${raised} raised of ₹${goal}`,
    },
    social: {
      title: 'Field Intel Stream',
      filterLabel: 'Choose a mission focus to refine verified posts.',
      donate: 'Mobilise',
      progressLabel: 'secured for mission',
    },
    distress: {
      title: 'Distress Signal Count',
      tabs: {
        sos: 'SOS',
        media: 'Media Upload',
      },
      detail: {
        date: 'Date',
        time: 'Time',
        geo: 'Geo-location',
        mediaType: 'Media type',
        media: 'Media',
        feedback: 'Feedback (if any)',
      },
    },
    resourcesHandle: {
      title: 'Resource Handle',
      subtitle: 'संसाधन प्रबंधन',
      used: 'Resources Used',
      received: 'Resources Received',
      reservoir: 'Reservoir',
    },
    services: {
      title: 'Available Service',
      states: 'List Of States',
      districts: 'List Of Districts',
      list: 'List',
    },
    contributions: {
      made: 'Contribution Made',
      received: 'Contribution Received',
    },
  },
  hi: {
    homeTitle: 'कमांड सेंटर',
    homeSubtitle: 'संगठित आपातकालीन निगरानी।',
    getHelp: 'अभी मदद लें',
    mediaUpload: 'मीडिया अपलोड',
    mediaUploadFull: 'Media Upload / मीडिया अपलोड',
    mediaHint: 'वॉयस, कैमरा या गैलरी प्रमाण जोड़ें।',
    sosButton: 'SOS',
    sosSubtitle: 'आपातकालीन संकट सिग्नल',
    profileTooltip: 'प्रोफ़ाइल खोलें',
    navigation: {
      ngo: 'एनजीओ',
      social: 'सोशल मीडिया',
      home: 'होम/SOS',
      resources: 'संसाधन',
      revelation: 'रिवेलेशन',
    },
    revelationTitle: 'रिवेलेशन डेस्क',
    revelationPlaceholder: 'घटना, स्थान, वाहन या जुड़े जोखिम के बारे में लिखें…',
    revelationHint: 'वॉयस/कैमरा/गैलरी अटैचमेंट जोड़ें।',
    revelationSubmit: 'रिवेलेशन सबमिट करें',
    loginTitle: 'वापस स्वागत है',
    loginCta: 'जारी रखें',
    otpTitle: 'प्रवेश सत्यापित करें',
    otpCta: 'कमांड सेंटर में प्रवेश करें',
    confirmationTitle: 'सिग्नल मिला',
    confirmationSubtitle: 'टीम्स सक्रिय हैं और आपसे संपर्क करेंगी।',
    confirmationDetails:
      'एकीकृत कमांड सेंटर ने केस आईडी आवंटित कर दी है। आप समीक्षा या अपडेट साझा कर सकते हैं।',
    confirmationPrimary: 'डैशबोर्ड पर लौटें',
    confirmationSecondary: 'रिपोर्ट साझा करें',
    ngo: {
      title: 'साझेदार एनजीओ ग्रिड',
      subtitle: 'कमांड स्तर अनुसार सत्यापित संगठनों को छांटें और तैनात करें।',
      filters: {
        district: 'जिला कमांड',
        state: 'राज्य नोड्स',
        national: 'राष्ट्रीय',
        global: 'वैश्विक',
      },
      raisedLabel: (raised, goal) => `₹${raised} जुटाए / ₹${goal}`,
    },
    social: {
      title: 'मैदान इंटेल स्ट्रीम',
      filterLabel: 'मिशन फोकस चुनें और पोस्ट छांटें।',
      donate: 'मूविलाइज़',
      progressLabel: 'मिशन के लिए सुरक्षित',
    },
    distress: {
      title: 'संकट संकेत गणना',
      tabs: {
        sos: 'SOS',
        media: 'मीडिया अपलोड',
      },
      detail: {
        date: 'तारीख',
        time: 'समय',
        geo: 'स्थान',
        mediaType: 'मीडिया प्रकार',
        media: 'मीडिया',
        feedback: 'प्रतिक्रिया (यदि कोई)',
      },
    },
    resourcesHandle: {
      title: 'रिसोर्स हैंडल',
      subtitle: 'संसाधन प्रबंधन',
      used: 'उपयोग संसाधन',
      received: 'प्राप्त संसाधन',
      reservoir: 'रिज़र्वायर',
    },
    services: {
      title: 'उपलब्ध सेवा',
      states: 'राज्य सूची',
      districts: 'जिला सूची',
      list: 'सूची',
    },
    contributions: {
      made: 'योगदान किया',
      received: 'योगदान प्राप्त',
    },
  },
};
